export const appRoutes = {
  splash: 'Splash',
  home: 'Home',
  drawer: 'Drawer',
  drawer: 'Drawer',
  keyOfficials: 'Key Officials',

  stateGovernment: 'State Government',
  successStories: 'Success Stories',
  detail: 'Detail',
  ourGovernment: 'Our Government',
  events: 'Events',
  gallery: 'Photo Gallery',
  listOfCms: 'List of former CMs',
  writeToCm: 'Write to CM',
  cmSpeeches: 'CM Speeches',
  feedBack: 'Feedback & Suggestion',
  cmReliefFund: 'CM Relief Fund',
  cmQuotes: 'CM Quotes',
  pressRelease: 'Press Releases',
  awards: 'Awards',
  megaEvents: 'Mega Events',
  galleryDetail:'Gallery Detail',
  photoBooth:'Photo Booth'
};
